### ISSUE TITLE
Dashboard Review!

### ISSUE THREAD

**Issue by auremoser** [mozillascience/studyGroupStats#1]
Looks excellent! Well done getting the graphs to work @AnamikaD !

Only a few updates!:

* [x] would you be able to `target="_blank"` the links in the left sidebar, that is, open them in a new tab, so they open new windows? Since that sidebar navigation isn't available at all of those links, it would be nice to keep the "dashboard" page open for the user.
* [x] any luck adjusting the graphs to match the colors (you can actually pick whatever palette you'd like, it doesn't have to be [this one](http://www.colorhexa.com/587dd6)
![screen shot 2017-08-25 at 1 03 33 am](https://user-images.githubusercontent.com/1559703/29700290-594de9ee-8931-11e7-97bd-65fb2bce2097.png)

* [x] this sounds silly but is there a way we can style the links in the text so that they look like "links" (underlined and [blue]())? I just noticed that it's kind of hard to see that you can click on the links in this statement, because of the way they are styled: 
> These data come from our Study Group Map Countries, and you can find that dataset here and the map here

Otherwise everything is excellent and thank you so much for all your hard work here!

**Comment by WW-Web-Infra** [comment]
@auremoser Thank you so much for the feedback! On it :dancer:

**Comment by WW-Web-Infra** [comment]
@auremoser about the graph color change, I tried to use tetradic color, can you give me some pointers to the color? Do you want the graphs to be in same shade?
I have changed color of graphs! Please check it

**Comment by auremoser** [comment]
I think it would be nice to have a mix of the tetradic colors (maybe each graph is a different one of those. I also like the ["flat UI palette"](https://flatuicolors.com/) so if those hexes are easier to use you're welcome to do that too. 

For C3.js, you should be able to alter colors by changing the parameters in each graph:
 * here for [data driven color](http://c3js.org/samples/data_color.html)
* here for [patterns](http://c3js.org/samples/options_color.html)

Does that make sense?

**Comment by WW-Web-Infra** [comment]
@auremoser  I used [flat UI colors](https://flatuicolors.com/). Please let me know for any changes!

Thank you for the reference, it was helful! <3

**Comment by auremoser** [comment]
Great! Thank you! It's great!

**Comment by WW-Web-Infra** [comment]
@auremoser any other changes or content requirement?

**Comment by auremoser** [comment]
It looks excellent!

I was looking at the stats and thinking that it might make sense to "average" the total members, like 72/#of study groups? It's weird that there are so few members, and I suspect that's because it's just the "organizers" who list themselves in the members.yml most times. It might be nice to instead have a stat for # of forks? I think we have 400-some forks now. And say something like:

> Study Group Leads "fork" the Study Group site on github and customize that template according to their own events, members, languages and color preferences

If you are tired, don't do this though, I can do it later!

**Comment by WW-Web-Infra** [comment]
No @auremoser ! I will do it!.. So do you want any graph changes?? Or just content.
The total study group was calculated as to count number of folder [data](https://github.com/auremoser/sg-events/tree/master/data)

**Comment by auremoser** [comment]
Cool, graphs look great. Thanks.

**Comment by WW-Web-Infra** [comment]
what can we do about total members?

**Comment by auremoser** [comment]
We could remove it? I'm not sure it's an accurate reflection of the study group member count.

**Comment by WW-Web-Infra** [comment]
Ya sure! I hope that the graph that shows member doesn't need any changes.

**Comment by auremoser** [comment]
No that's fine!

**Comment by WW-Web-Infra** [comment]
It is done! Can you review it ?

**Comment by auremoser** [comment]
Did you add the "forks" data? 
Good on removing the members info, but I think we can add a summary of the fork count (like the "quoted" comment above?). If not, no worries, but it was nice having 4 stats at the top. 

Otherwise, looks excellent. I'm not sure why the header for "Levels of Lessons" is slightly smaller than the "Study Group Activities" headers, but maybe we should match them.

Other than that, all is great! Thank you @AnamikaD ! You are amazing!

**Comment by WW-Web-Infra** [comment]
@auremoser I have added the total forks and and adjusted the headers! Please check it :D Thank you so much ! Any other changes? Can I submit my evaluations?

**Comment by auremoser** [comment]
Looks excellent, I love the little 🍴 symbol in the forks section !

Very nice work, well done, no more changes!

**Comment by WW-Web-Infra** [comment]
Thank you so much Aurelia! I am glad that you like it! Cheers to our 3 months 😘😘
